### ISSUE TITLE
0.6.10 couldn't start

### ISSUE THREAD

**Issue by xlucn** [ChromiumOS-Guy/uWolf#8]
Just happened to see the new release and tested. It crashed before doing anything.

The log messages points me to the script `librewolf.sh` L37

https://github.com/ChromiumOS-Guy/uWolf/blob/ef3d961a0ae2a24746ae695d2b641bbc030934e6/librewolf.sh#L35-L37

`yaml_data` is `None`, causing the L37 to fail. Maybe catch that case as well?

---

In my phone (Poco X3 NFC), the mentioned file is empty:
```
$ cat /etc/deviceinfo/devices/halium.yaml 
# Empty device config
# Intended for use as a bind-mount overlay target, like device-specific Halium ports.
```

But the information are in 
```
$ cat /etc/deviceinfo/default.yaml 
defaults:
  default:
    Name: generic
    PrettyName: Generic device
    DeviceType: desktop
    GridUnit: 8
    SupportedOrientations:
      - Portrait
      - InvertedPortrait
      - Landscape
      - InvertedLandscape
    PrimaryOrientation: Landscape
    PortraitOrientation: Portrait
    InvertedPortraitOrientation: InvertedPortrait
    LandscapeOrientation: Landscape
    InvertedLandscapeOrientation: InvertedLandscape
    WebkitDpr: 1

  halium:
    Name: generic
    PrettyName: Generic Halium device
    DeviceType: phone
    GridUnit: 21
    WebkitDpr: 2
    PrimaryOrientation: Portrait

  phone:
    GridUnit: 21
    WebkitDpr: 2
    PrimaryOrientation: Portrait

  tablet:
    GridUnit: 21
    WebkitDpr: 2
    PrimaryOrientation: Landscape

  desktop:
    GridUnit: 8
    PrimaryOrientation: Landscape
```

**Comment by ChromiumOS-Guy** [comment]
here is example:
```
phablet@ubuntu-phablet:~$ cat /etc/deviceinfo/devices/halium.yaml
billie2:
  Vendor: OnePlus
  codename: billie2
  Names:
    - Nord N100
    - billie2
    - OnePlus Nord N100
  PrettyName: OnePlus Nord N100
  DeviceType: phone
  GridUnit: 16
  SupportedOrientations:
    - Portrait
    - Landscape
    - InvertedLandscape
  BacklightSysfsPath:
    - /sys/class/backlight/panel0-backlight
  FlashlightSysfsPath:
    - /sys/class/leds/led:torch_0/brightness
  FlashlightSwitchPath:
    - /sys/class/leds/led:switch_0/brightness
  MirAndroidPlatformServerBackpressure:
    - false
  MirAndroidPlatformServerPartialUpdates:
    - true
  MirAndroidPlatformServerEglSync:
    - false
  MirAndroidPlatformClientEglFlush:
    - "all"
  XwaylandShm:
    - true
  OfonoPlugin: binder
  OfonoImplementsIms: true
```

i can catch that and make it default to phone for sure, the defaults.yaml is useless its a template
